@startuml
class Environment {
    + Title : string <<get>> <<set>>
}
class "ICollection`1"<T> {
}
Environment --> "Id" Guid
Environment --> "Participants<EnvironmentParticipant>" "ICollection`1"
Environment --> "Story" Story
Environment --> "CreatedAt" DateTime
@enduml
