@startuml
!include .\\ApplicationUser.puml
!include .\\Environment.puml
!include .\\EnvironmentParticipant.puml
!include .\\Quiz.puml
!include .\\QuizChoice.puml
!include .\\QuizQuestion.puml
!include .\\QuizResult.puml
!include .\\Story.puml
!include .\\StoryChoice.puml
!include .\\StoryPart.puml
!include .\\StoryPreset.puml
!include .\\StoryPresetPart.puml
@enduml
