@startuml
class QuizQuestion {
    + Number : int <<get>> <<set>>
    + Text : string <<get>> <<set>>
    + IsMultipleChoice : bool <<get>> <<set>>
}
class "ICollection`1"<T> {
}
QuizQuestion --> "Id" Guid
QuizQuestion --> "Choices<QuizChoice>" "ICollection`1"
QuizQuestion --> "Results<QuizResult>" "ICollection`1"
@enduml
