@startuml
class StoryPart {
    + Text : string <<get>> <<set>>
}
class "ICollection`1"<T> {
}
StoryPart --> "Id" Guid
StoryPart --> "Story" Story
StoryPart --> "Choices<StoryChoice>" "ICollection`1"
StoryPart --> "CreatedAt" DateTime
@enduml
