@startuml
class StoryPresetPart {
    + Text : string <<get>> <<set>>
    + ChoiceNumber : int <<get>> <<set>>
    + ChoiceText : string <<get>> <<set>>
}
class "ICollection`1"<T> {
}
StoryPresetPart --> "Id" Guid
StoryPresetPart --> "PreviousId" Guid
StoryPresetPart --> "NextParts<StoryPresetPart>" "ICollection`1"
@enduml
